### ISSUE TITLE
Error: failed to download "ot-helm/redis-operator"

### ISSUE THREAD

**Issue by cdemi** [OT-CONTAINER-KIT/helm-charts#17] opened 2022-01-11 11:57 UTC
Following the documentation instructions:
`helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis-operator` does not work because it looks like the latest `redis-operator-0.9.0` is not available as a release on GitHub. I can see `Redis 0.9.0` but not `Redis Operator`

```Error: failed to fetch https://github.com/OT-CONTAINER-KIT/helm-charts/releases/download/redis-operator-0.9.0/redis-operator-0.9.0.tgz : 404 Not Found```

**Comment by andre-lx** [comment] 2022-01-12 12:00
Having the same issue. 

```
helm pull ot-helm/redis-operator
Error: failed to fetch https://github.com/OT-CONTAINER-KIT/helm-charts/releases/download/redis-operator-0.9.0/redis-operator-0.9.0.tgz : 404 Not Found
```

And looking at the releases tab you can see that the file doesn't exist:
https://github.com/OT-CONTAINER-KIT/helm-charts/releases/tag/redis-operator-0.9.0

**Comment by TanZng** [comment] 2022-01-12 17:48
Same issue here
```
➜ helm upgrade redis-operator ot-helm/redis-operator \
    --install --namespace redis-operator

Release "redis-operator" does not exist. Installing it now.
Error: failed to download "ot-helm/redis-operator"
```

**Comment by vincentbaeten** [comment] 2022-01-13 22:17
Same here

**Comment by bleleve** [comment] 2022-01-17 12:56
Same here. Seems to be related to https://github.com/OT-CONTAINER-KIT/helm-charts/runs/4366139164?check_suite_focus=true#step:6:15

Is there a pilot on the plane ? :)

**Comment by pkutishch** [comment] 2022-01-24 07:29
+1 to the issue, had to bypass via specifying version to the helm install command
`--version 0.8.0`

**Comment by kvendingoldo** [comment] 2022-02-03 18:44
any updates here?

**Comment by kuzm1ch** [comment] 2022-02-09 15:38
helm operator was fixed. 
`helm pull ot-helm/redis-operator` works fine. But there is an issue with another chart. 
```
helm pull  ot-helm/redis-cluster  
Error: failed to fetch https://github.com/OT-CONTAINER-KIT/helm-charts/releases/download/redis-cluster-0.9.0/redis-cluster-0.9.0.tgz : 404 Not Found
```

**Comment by dm3ch** [comment] 2022-02-11 21:18
The problem is that CRDs contains unresolved git conflicts in master - like this https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-operator/crds/redis-cluster.yaml#L6288

@iamabhishek-dubey as a maintainer could you please fix git conflicts as a mand release working version of the chart.

**Comment by jakuzure** [comment] 2022-02-22 12:45
+1 for redis-cluster
`helm search repo ot-helm` says 0.9.0 is the latest version, but it can't be downloaded, switching to 0.8.0 works for now

**Comment by kvendingoldo** [comment] 2022-02-22 14:58
@jakuzure `0.10.1` works

**Comment by apena-matriz** [comment] 2022-02-22 19:04
> @jakuzure `0.10.1` works

If you install `redis-operator` v0.10.1 you cannot install `redis-cluster` v0.9.0 because is not available (as @kuzm1ch said). Also, you cannot install `redis-cluster` v0.8.0 because it is not compatible:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RedisCluster.spec.kubernetesConfig): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.kubernetesConfig, ValidationError(RedisCluster.spec.redisFollower): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisFollower, ValidationError(RedisCluster.spec.redisLeader): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisLeader]
```

**Comment by apena-matriz** [comment] 2022-02-24 18:28
@dm3ch 
The [redis-cluster.yaml](https://github.com/dm3ch/opstree-helm-charts/blob/main/charts/redis-cluster/templates/redis-cluster.yaml) in your chart has a wrong indentation in lines 18 and 28. The sentences should be at the beginning of the line.

If you try to install the chart with _nodeAffinity_, _podAffinity_ or _podAntiAffinity_ you will get the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RedisCluster.spec.redisFollower.affinity): unknown field "requiredDuringSchedulingIgnoredDuringExecution" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisFollower.affinity, ValidationError(RedisCluster.spec.redisLeader.affinity): unknown field "requiredDuringSchedulingIgnoredDuringExecution" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisLeader.affinity]
```

**Comment by dm3ch** [comment] 2022-02-24 19:01
> @dm3ch The [redis-cluster.yaml](https://github.com/dm3ch/opstree-helm-charts/blob/main/charts/redis-cluster/templates/redis-cluster.yaml) in your chart has a wrong indentation in lines 18 and 28. The sentences should be at the beginning of the line.
> 
> If you try to install the chart with _nodeAffinity_, _podAffinity_ or _podAntiAffinity_ you will get the following error:
> 
> ```
> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RedisCluster.spec.redisFollower.affinity): unknown field "requiredDuringSchedulingIgnoredDuringExecution" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisFollower.affinity, ValidationError(RedisCluster.spec.redisLeader.affinity): unknown field "requiredDuringSchedulingIgnoredDuringExecution" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisLeader.affinity]
> ```

Thank you for answer - I would test.
Actually, I haven't changed anything connected to affinity in my fork, so it's an upstream problem.

Prepared PR with fix of that issue https://github.com/OT-CONTAINER-KIT/helm-charts/pull/25 and I've merged it to my main branch, resulting new version - https://github.com/dm3ch/opstree-helm-charts/releases/tag/redis-cluster-0.9.2

**Comment by aaahy** [comment] 2022-03-25 13:55
`
[root@master ot-container-kit]# helm upgrade redis-cluster ot-helm/redis-cluster --set redisCluster.clusterSize=3 --install --namespace ot-operators
Release "redis-cluster" does not exist. Installing it now.
Error: failed to download "ot-helm/redis-cluster"

[root@master ot-container-kit]# helm pull  ot-helm/redis-cluster  
Error: failed to fetch https://github.com/OT-CONTAINER-KIT/helm-charts/releases/download/redis-cluster-0.9.0/redis-cluster-0.9.0.tgz : 404 Not Found
`

I can not install redis-cluster like above。

**Comment by iamabhishek-dubey** [comment] 2022-03-30 17:56
This should be fixed now.

**Closed by iamabhishek-dubey** 2022-03-30 17:56 UTC
