### ISSUE TITLE
redis-operator chart v0.13 has error in CRDs

### ISSUE THREAD

**Issue by ahgraber** [OT-CONTAINER-KIT/helm-charts#61] opened 2023-01-16 15:56 UTC
While trying to install redis-operator version 0.13.0, I receive the following error:

```
Helm install failed: failed to parse CRDs from crds/redis.yaml: error parsing : error converting YAML to JSON: yaml: line 1920: could not find expected ':'
```

**Comment by remi-sap** [comment] 2023-01-17 09:47
Likely duplicate of https://github.com/OT-CONTAINER-KIT/helm-charts/issues/62

**Closed** 2023-02-20 17:47 UTC
